spring.application.name=task-manager

# --- Configuração de Banco de Dados ---
spring.datasource.url=jdbc:mysql://localhost:3306/db_task_manager?allowPublicKeyRetrieval=true&serverTimezone=America/Sao_Paulo&useSSL=false
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# --- Configuração JPA / Hibernate ---
# O Hibernate valida a estrutura gerada pelas migrations do Flyway sem alterar o banco
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.database=mysql
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# --- Configuração Flyway ---
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=true

# --- Jackson (Datas em JSON) ---
spring.jackson.date-format=yyyy-MM-dd HH:mm:ss
spring.jackson.time-zone=America/Sao_Paulo

